global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:8000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "celery"
    metrics_path: /metrics
    static_configs:
      - targets: ["celery:5555"]

  - job_name: "otel-collector"
    metrics_path: /metrics
    static_configs:
      - targets: ["otel-collector:8888"]
